version: "2.1"
services:
  # APP  ***************************************************************************************
  apigatewayservice:
    image: linktech/apigatewayservice
    build: 
      context: ./apigateway/target
    ports:
    - 8080:8080
    links:
    - mongo
    - authservice
    - institutionsservice
    - messagesservice
    - postsservice
    - userservice
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"

  authservice:
      image: linktech/authservice
      build: 
        context: ./authservice/target/
      ports:
      - 3303:3303
      links:
      - mongo
      entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
      
  institutionsservice:
    image: linktech/institutionsservice
    build: 
      context: ./institutionsservice/target/
    ports:
    - 2002:2002
    links:
    - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
    
  messagesservice:
    image: linktech/messagesservice
    build: 
      context: ./messagesservice/target/
    ports:
    - 2212:2212
    links:
    - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"

  postsservice:
    image: linktech/postsservice
    build: 
      context: ./postsservice/target/
    ports:
    - 2303:2303
    links:
    - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"

  userservice:
    image: linktech/userservice
    build: 
      context: ./userservice/target/
    ports:
    - 2202:2202
    links:
    - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"

  mongo:
    image: mongo:3.2.4
    ports:
    - 27017:27017
    command: --smallfiles

  mongo-client:
    image: mongoclient/mongoclient
    ports:
    - 3030:3000
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017
    links:
      - mongo
