# FROM ubuntu:18.04


# # Install Java
# RUN apt-get update && \
#     DEBIAN_FRONTEND=noninteractive \
#     apt-get -y install default-jre-headless && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

# # Install MongoDB.
# RUN \
#   apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 && \
#   echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' > /etc/apt/sources.list.d/mongodb.list && \
#   apt-get update && \
#   apt-get install -y mongodb-org && \
#   rm -rf /var/lib/apt/lists/*

# # Define mountable directories.
# VOLUME ["/data/db"]

# # Define working directory.
# WORKDIR /data

# # Define default command.
# CMD ["mongod"]

# # Expose ports.
# #   - 27017: process
# #   - 28017: http
# EXPOSE 27017
# EXPOSE 28017




FROM openjdk:8-jdk-alpine
# EXPOSE 8080 8080
COPY apigateway-0.0.1-SNAPSHOT.jar app.jar
# COPY authservice-0.0.1-SNAPSHOT.jar authservice.jar
# COPY institutionsservice-0.0.1-SNAPSHOT.jar institutionsservice.jar
# COPY messagesservice-0.0.1-SNAPSHOT.jar messagesservice.jar
# COPY postsservice-0.0.1-SNAPSHOT.jar postsservice.jar
# COPY userservice-0.0.1-SNAPSHOT.jar userservice.jar
# COPY serve.sh serve.sh
# RUN \
#   apk add --no-cache bash
# ENTRYPOINT /bin/bash serve.sh
# ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
ENV JAVA_OPTS=""
ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar
# CMD [ "bin/bash", "./serve.sh" ] 

##Check this : https://technology.amis.nl/2018/03/18/running-spring-boot-in-a-docker-container-on-openjdk-oracle-jdk-zulu-on-alpine-linux-oracle-linux-ubuntu/